### ISSUE TITLE
Merging functionality

### ISSUE THREAD

**Issue by owencqueen** [CS340-21/MathMajorsUnite#56]
On the backend, we need some efficient way to merge CSV files and save them locally. This function should be able to do the following:

Arguments:
1) list of pandas dataframes

Returns:
-1 if files were not able to be merged
0 if files were able to be merged

This function should be able to check if the files are able to be merged. Just try to indicate if there is an error or not in the return, I can show an error message on the front end if needed.

It should also be able to save the merged dataframe to the location from which the other dataframes were loaded. If you want to, you could return the merged dataframe and I could save it from the frontend.

**Comment by uncrewedimp** [comment]
These are merging columns, not rows.  For example, if you have columns ABCD in one file and EFG in the other file, then the merged file will have ABCDEFG.
